FROM ubuntu:16.04
MAINTAINER Shinichi Awamoto <sap.pcmail@gmail.com>

RUN apt update
RUN apt install -y cmake git build-essential
RUN git clone git://github.com/cpputest/cpputest.git
RUN mkdir workspace install
WORKDIR workspace
RUN cmake -DCMAKE_INSTALL_PREFIX=../install -DCOVERAGE=ON ../cpputest
RUN make -j$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
RUN make install

